### ISSUE TITLE
A better home for barrier monitoring

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-health#10]
There is obviously a danger of increasing the size of the article app with this but I was wondering whether it might make sense to put these barrier tests into next-article…

Then each app could have monitoring that most logically belonged with it alongside the code rather than a single monitoring app like this?

Wondered what you thought @aintgoin2goa

**Comment by aintgoin2goa** [comment]
I don't agree, tbh - barriers are not part of the article app as such, it just so happens that only the article app needs to display them.  Also, those tests are not testing barriers - they are testing the entire paywall (of which barriers is just a small but visible part).

In my ideal world barriers would be entirely separate from the article app and if we started doing ESI or something they would be.

**Comment by matthew-andrews** [comment]
Yeah I don't think I agree with Jul 27 Matt anymore either — this solution has been working well.
